language: python

python:
  - 3.6

services:
  - mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=eris_hub.settings.travis
  - export PIP_USE_MIRRORS=true
  - sudo apt-get install python3-dev libmysqlclient-dev

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS eris_test;'

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
